apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Backstage
  description: Backstage for TFB
  # labels:
  #   example.com/custom: custom_label_value
  annotations:
    backstage.io/kubernetes-namespace: coder
  tags:
    - backstage
spec:
  type: service
  lifecycle: experimental
  owner: theflyingbirdsmc/services
  # system: eu
  # domain: tfb-network