apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: portal
  description: TFB Developer Portal
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: theflyingbirds1@gmail.com
  lifecycle: experimental
